site_name: Python A.DS
nav:
    - Home: index.md
    - Chapters 1-7:
        - 2. Backtracking: chapters/backtracking.md
        - 1. Introduction: chapters/introduction.md
        - 0. Organization: chapters/organization.md
    - Quick Review: review.md
    - Log: log.md
theme: mkdocs
