site_name: Python DS
nav:
    - Home: index.md
    - Chapters 1-7:
        - 3. Linked List: chapters/linkedlist.md
        - 2. Backtracking: chapters/backtracking.md
        - 1. Introduction: chapters/introduction.md
        - 0. Organization: chapters/organization.md
    - Programs:
        - Linked List: programs/linked_list.md
        - Hash Table: programs/hash_table.md
    - Quick Review: review.md
    - Log: log.md
theme: mkdocs
